const KEY="naskhu-service-requests";const $=s=>document.querySelector(s);let requests=JSON.parse(localStorage.getItem(KEY)||"[]");
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function save(){localStorage.setItem(KEY,JSON.stringify(requests));render()}
function formatDate(v){if(!v)return"Not scheduled";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
function counts(){const c=s=>requests.filter(r=>r.status===s).length;$("#newCount").textContent=c("New");$("#quotedCount").textContent=c("Quoted");$("#confirmedCount").textContent=c("Confirmed")+c("Scheduled");$("#completedCount").textContent=c("Completed")}
function render(){counts();const q=$("#search").value.toLowerCase().trim(),status=$("#filterStatus").value;const list=requests.filter(r=>(status==="All"||r.status===status)&&`${r.id} ${r.name} ${r.phone} ${r.service} ${r.location}`.toLowerCase().includes(q));$("#requestCount").textContent=`${list.length} of ${requests.length} requests`;$("#requestList").innerHTML=list.length?list.map(r=>`<article class="request-card"><div class="request-top"><div><h3>${esc(r.service)}</h3><p>${esc(r.id)} · ${esc(r.name)} · ${esc(r.phone)}</p></div><span class="badge ${esc(r.status)}">${esc(r.status)}</span></div><div class="request-meta"><div><small>Location</small><strong>${esc(r.location||"—")}</strong></div><div><small>Priority</small><strong>${esc(r.priority||"Normal")}</strong></div><div><small>Scheduled</small><strong>${esc(formatDate(r.scheduledAt))}</strong></div><div><small>Quote</small><strong>${esc(r.amount||"Not set")}</strong></div></div><p class="description">${esc(r.description||"No description")}</p><div class="card-actions"><button data-edit="${esc(r.id)}">Edit</button><button data-status="Quoted" data-id="${esc(r.id)}">Mark quoted</button><button data-status="Confirmed" data-id="${esc(r.id)}">Confirm</button><button data-calendar="${esc(r.id)}">Add to calendar</button><button data-whatsapp="${esc(r.id)}">WhatsApp</button><button class="danger" data-delete="${esc(r.id)}">Delete</button></div></article>`).join(""):`<div class="empty">No requests match this view.</div>`}
function clearForm(){$("#requestForm").reset();$("#editId").value="";$("#status").value="New";$("#priority").value="Normal";$("#requestForm").classList.add("hidden")}
function openForm(r){$("#requestForm").classList.remove("hidden");if(r){$("#editId").value=r.id;["name","phone","service","location","description","status","priority","scheduledAt","amount","notes"].forEach(k=>{const e=$("#"+k);if(e)e.value=r[k]||""})}window.scrollTo({top:0,behavior:"smooth"})}
function calendarFile(r){if(!r.scheduledAt)return alert("Set a scheduled date and time first.");const start=new Date(r.scheduledAt),end=new Date(start.getTime()+60*60*1000),fmt=d=>d.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z");const text=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Naskhu IT Solutions//Service Manager//EN","BEGIN:VEVENT",`UID:${r.id}@naskhu-it`, `DTSTAMP:${fmt(new Date())}`,`DTSTART:${fmt(start)}`,`DTEND:${fmt(end)}`,`SUMMARY:${r.service.replace(/,/g,"\\,")}`,`DESCRIPTION:${(r.description||"").replace(/\n/g,"\\n").replace(/,/g,"\\,")}`,`LOCATION:${(r.location||"").replace(/,/g,"\\,")}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/calendar"}));a.download=`${r.id}.ics`;a.click();URL.revokeObjectURL(a.href)}
$("#toggleForm").addEventListener("click",()=>openForm());$("#cancelEdit").addEventListener("click",clearForm);$("#search").addEventListener("input",render);$("#filterStatus").addEventListener("change",render);
$("#requestForm").addEventListener("submit",e=>{e.preventDefault();const old=requests.find(r=>r.id===$("#editId").value);const r={id:old?.id||`Q-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`,name:$("#name").value.trim(),phone:$("#phone").value.trim(),service:$("#service").value.trim(),location:$("#location").value.trim(),description:$("#description").value.trim(),status:$("#status").value,priority:$("#priority").value,scheduledAt:$("#scheduledAt").value,amount:$("#amount").value.trim(),notes:$("#notes").value.trim(),createdAt:old?.createdAt||new Date().toISOString()};const i=requests.findIndex(x=>x.id===r.id);i>=0?requests[i]=r:requests.unshift(r);save();clearForm()});
$("#requestList").addEventListener("click",e=>{const id=e.target.dataset.id||e.target.dataset.edit||e.target.dataset.calendar||e.target.dataset.whatsapp||e.target.dataset.delete;if(!id)return;const r=requests.find(x=>x.id===id);if(e.target.dataset.edit)openForm(r);if(e.target.dataset.status){r.status=e.target.dataset.status;save()}if(e.target.dataset.calendar)calendarFile(r);if(e.target.dataset.whatsapp)window.location.href=`https://wa.me/960${String(r.phone).replace(/\D/g,"").replace(/^960/,"")}?text=${encodeURIComponent(`Hello ${r.name}, regarding your ${r.service} request (${r.id}).`)}`;if(e.target.dataset.delete&&confirm("Delete this request?")){requests=requests.filter(x=>x.id!==id);save()}});render();