const WHATSAPP_NUMBER="9607988774";
const REQUEST_KEY="naskhu-service-requests";
const services=[
{category:"Networking",icon:"🌐",name:"Network Design & Installation",description:"LAN design, structured cabling, racks, switches, routers and complete office network deployment."},
{category:"Networking",icon:"🔀",name:"Switch, VLAN & Router Configuration",description:"Cisco, Huawei, MikroTik and UniFi configuration, VLANs, trunks, routing and troubleshooting."},
{category:"Networking",icon:"🛡️",name:"Firewall & VPN Setup",description:"Secure remote access, site-to-site VPNs, firewall policies and internet security hardening."},
{category:"Wi-Fi",icon:"📶",name:"Home Wi-Fi Setup",description:"Router placement, mesh Wi-Fi, dead-zone removal and secure home wireless setup."},
{category:"Wi-Fi",icon:"📡",name:"Office Wi-Fi Installation",description:"Business Wi-Fi design, access points, guest networks, roaming and coverage optimization."},
{category:"Wi-Fi",icon:"📊",name:"Wi-Fi Survey & Troubleshooting",description:"Coverage assessment, interference checks, slow Wi-Fi diagnosis and performance tuning."},
{category:"Security",icon:"📹",name:"CCTV Installation",description:"IP cameras, NVR/DVR setup, cabling, storage planning and remote mobile viewing."},
{category:"Security",icon:"🔐",name:"Smart Door Lock Installation",description:"Fingerprint, PIN, card and app-enabled smart lock installation and configuration."},
{category:"Security",icon:"🚪",name:"Access Control & Video Doorbells",description:"Door access systems, attendance devices, intercoms and smart video doorbells."},
{category:"Security",icon:"👶",name:"Baby Monitor Setup",description:"Secure camera placement, Wi-Fi setup, mobile viewing and notification configuration."},
{category:"Servers",icon:"🖥️",name:"Windows & Linux Server Setup",description:"Server installation, hardening, users, storage, services and remote management."},
{category:"Servers",icon:"🏢",name:"Active Directory & File Server",description:"Domain services, permissions, shared storage, group policies and centralized management."},
{category:"Servers",icon:"💾",name:"NAS, Backup & Virtualization",description:"NAS deployment, backup strategy, VMware, Hyper-V and disaster recovery planning."},
{category:"Cloud",icon:"☁️",name:"Microsoft 365 & Email",description:"Business email, Microsoft 365 setup, licensing, migration and user administration."},
{category:"Cloud",icon:"🌩️",name:"Cloud Backup & Migration",description:"Secure cloud storage, backup automation, data migration and remote access solutions."},
{category:"Web & Software",icon:"🌍",name:"Business Website Development",description:"Responsive company websites, service websites, portfolios and landing pages."},
{category:"Web & Software",icon:"🛒",name:"Online Shops & Booking Systems",description:"E-commerce websites, catalogues, appointment booking and WhatsApp ordering systems."},
{category:"Web & Software",icon:"⚙️",name:"Custom Software & Automation",description:"Internal tools, dashboards, reports, database systems and business workflow automation."},
{category:"IT Support",icon:"💻",name:"Computer, Printer & Scanner Setup",description:"PC setup, upgrades, printer/scanner installation, troubleshooting and office support."},
{category:"IT Support",icon:"🏬",name:"Office IT Setup",description:"Complete setup for new offices including network, Wi-Fi, computers, printers and security."},
{category:"IT Support",icon:"🧰",name:"Remote & On-site Support",description:"Technical troubleshooting, maintenance visits, emergency support and annual contracts."},
{category:"Consultancy",icon:"📋",name:"IT Consultancy & Project Planning",description:"Technology assessment, equipment selection, project design, budgeting and implementation planning."}
];
const $=s=>document.querySelector(s);let activeCategory="All";
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2200)}
function renderCategories(){const cats=["All",...new Set(services.map(s=>s.category))];$("#categoryChips").innerHTML=cats.map(c=>`<button class="category-chip ${c===activeCategory?"active":""}" data-category="${c}" type="button">${c}</button>`).join("")}
function renderServices(){const q=$("#searchInput").value.toLowerCase().trim();const list=services.filter(s=>(activeCategory==="All"||s.category===activeCategory)&&`${s.category} ${s.name} ${s.description}`.toLowerCase().includes(q));$("#serviceGrid").innerHTML=list.length?list.map(s=>`<article class="service-card"><div class="service-icon">${s.icon}</div><span class="service-category">${s.category}</span><h3>${s.name}</h3><p>${s.description}</p><button class="quote-service-button" type="button" data-service="${s.name}" data-category="${s.category}">Request Quote</button></article>`).join(""):`<div class="empty-state"><h3>No services found</h3><p>Try another keyword or category.</p></div>`}
function populateServices(category="",service=""){const cs=$("#serviceCategory"),ss=$("#specificService");const cats=[...new Set(services.map(s=>s.category))];cs.innerHTML=`<option value="">Choose category</option>${cats.map(c=>`<option>${c}</option>`).join("")}<option>Other</option>`;if(category)cs.value=category;const selected=cs.value;const list=selected&&selected!=="Other"?services.filter(s=>s.category===selected):services;ss.innerHTML=`<option value="">Choose service</option>${list.map(s=>`<option>${s.name}</option>`).join("")}<option>Other IT service</option>`;if(service)ss.value=service}
function selectService(category,service){populateServices(category,service);$("#quote").scrollIntoView({behavior:"smooth",block:"start"});setTimeout(()=>$("#customerName").focus(),450)}
function saveRequest(request){const all=JSON.parse(localStorage.getItem(REQUEST_KEY)||"[]");all.unshift(request);localStorage.setItem(REQUEST_KEY,JSON.stringify(all))}
function submitQuote(event){event.preventDefault();const request={id:`Q-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`,name:$("#customerName").value.trim(),phone:$("#customerPhone").value.trim(),company:$("#company").value.trim(),email:$("#email").value.trim(),location:$("#location").value.trim(),category:$("#serviceCategory").value,service:$("#specificService").value,description:$("#projectDescription").value.trim(),preferredDate:$("#preferredDate").value,budget:$("#budget").value.trim(),priority:$("#priority").value,status:"New",scheduledAt:"",createdAt:new Date().toISOString()};if(!request.name||!request.phone||!request.location||!request.category||!request.service||!request.description)return toast("Please complete all required fields");if($("#saveCopy").checked)saveRequest(request);const msg=[`*New IT Service Request — ${request.id}*`,"",`*Customer:* ${request.name}`,request.company?`*Company:* ${request.company}`:"",`*Phone:* ${request.phone}`,request.email?`*Email:* ${request.email}`:"",`*Location:* ${request.location}`,`*Category:* ${request.category}`,`*Service:* ${request.service}`,`*Priority:* ${request.priority}`,request.preferredDate?`*Preferred date:* ${request.preferredDate}`:"",request.budget?`*Budget:* ${request.budget}`:"","*Requirement:*",request.description,"","Please review and provide a quotation.","I will attach any relevant photos or documents in this chat."].filter(Boolean).join("\n");window.location.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`}
$("#categoryChips").addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;activeCategory=b.dataset.category;renderCategories();renderServices()});
$("#serviceGrid").addEventListener("click",e=>{const b=e.target.closest("[data-service]");if(b)selectService(b.dataset.category,b.dataset.service)});
document.querySelectorAll(".quick-service").forEach(b=>b.addEventListener("click",()=>selectService(b.dataset.category,b.dataset.service)));
$("#searchInput").addEventListener("input",renderServices);$("#serviceCategory").addEventListener("change",()=>populateServices($("#serviceCategory").value));$("#quoteForm").addEventListener("submit",submitQuote);
$("#themeButton").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("naskhu-services-theme",document.body.classList.contains("dark")?"dark":"light")});
if(localStorage.getItem("naskhu-services-theme")==="dark")document.body.classList.add("dark");renderCategories();renderServices();populateServices();